// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ckbyrfwnulexhxkdldto.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNrYnlyZndudWxleGh4a2RsZHRvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY1ODA0NjEsImV4cCI6MjA3MjE1NjQ2MX0.l8camiKXTRz9esxECZ3Mf_HVQjIvuXl0wl8wr7LHnj4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});